aws s3 cp s3://llched-raw/training_v0/nougat_processed_biorxiv_clean_test.jsonl     /scratch/kjablonk/nougat_processed_biorxiv_clean_test.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_biorxiv_clean_train.jsonl    /scratch/kjablonk/nougat_processed_biorxiv_clean_train.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_biorxiv_clean_valid.jsonl    /scratch/kjablonk/nougat_processed_biorxiv_clean_valid.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_chemrxiv_clean_test.jsonl    /scratch/kjablonk/nougat_processed_chemrxiv_clean_test.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_chemrxiv_clean_train.jsonl   /scratch/kjablonk/nougat_processed_chemrxiv_clean_train.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_chemrxiv_clean_valid.jsonl   /scratch/kjablonk/nougat_processed_chemrxiv_clean_valid.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_medrxiv_clean_test.jsonl     /scratch/kjablonk/nougat_processed_medrxiv_clean_test.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_medrxiv_clean_train.jsonl    /scratch/kjablonk/nougat_processed_medrxiv_clean_train.jsonl
aws s3 cp s3://llched-raw/training_v0/nougat_processed_medrxiv_clean_valid.jsonl    /scratch/kjablonk/nougat_processed_medrxiv_clean_valid.jsonl
