python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_biorxiv_clean_test.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_biorxiv_clean_test/
python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_biorxiv_clean_train.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_biorxiv_clean_train/
python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_biorxiv_clean_valid.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_biorxiv_clean_valid/

python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_chemrxiv_clean_test.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_chemrxiv_clean_test/
python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_chemrxiv_clean_train.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_chemrxiv_clean_train/
python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_chemrxiv_clean_valid.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_chemrxiv_clean_valid/

python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_medrxiv_clean_test.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_medrxiv_clean_test/
python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_medrxiv_clean_train.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_medrxiv_clean_train/
python open_lm/datapreprocess/make_2048.py --input-files /scratch/kjablonk/nougat_processed_medrxiv_clean_valid.jsonl --output-dir /scratch/kjablonk/preproc_data --num-workers 30 --num-consumers 8 --upload-to-s3 --s3-base-dir s3://llched-raw/open_lm_run_processed_data/nougat/nougat_processed_medrxiv_clean_valid/
